import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "hi";

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const en = {
  // Landing
  "landing.title": "Naam Jap Sewa",
  "landing.subtitle": "\"Haare ka Sahara, Baba Shyam Hamara\"",
  "landing.description": "Begin your daily sadhana in this digital temple. Dedicate your Naam Jaap to Khatu Shyam Ji, maintain your streak, and earn symbolic rewards for your devotion.",
  "landing.button": "Begin your sadhana",
  "landing.tab-login": "Login",
  "landing.tab-register": "Register",
  "landing.label-name": "Your Name",
  "landing.placeholder-name": "Enter full name",
  "landing.label-email": "Email",
  "landing.placeholder-email": "your@email.com",
  "landing.label-password": "Password",
  "landing.placeholder-password": "Password",
  "landing.forgot-password": "Forgot password?",
  "landing.btn-login": "Login",
  "landing.btn-register": "Create Account",
  "landing.btn-loading": "Please wait...",
  "landing.error-required": "Email and password are required",
  "landing.error-name-required": "Please enter your name",
  "landing.error-generic": "Something went wrong, please try again",

  // Layout Navigation
  "nav.jaap": "Jaap",
  "nav.dashboard": "Dashboard",
  "nav.leaderboard": "Leaderboard",
  "nav.wallet": "Wallet",
  "nav.history": "History",
  "nav.profile": "Profile",
  "nav.sankalp-board": "Sankalp Board",
  "nav.mera-sankalp": "My Sankalp",
  "nav.admin": "Admin",
  "nav.logout": "Logout",
  "nav.payout": "Payout",

  // Dashboard (Bhakt)
  "dashboard.title": "Dashboard",
  "dashboard.subtitle": "Your sadhana overview",
  "dashboard.daily-target": "Daily Target",
  "dashboard.total-jaaps": "Total Jaaps",
  "dashboard.streak": "Streak",
  "dashboard.todays-earnings": "Today's Earnings",
  "dashboard.total-earnings": "Total Earnings",
  "dashboard.daily-history": "Last 7 Days",
  "dashboard.global-stats": "Global Temple",
  "dashboard.global-desc": "Collective devotion of all devotees",
  "dashboard.global-jaap-count": "Global Jaap Count",
  "dashboard.todays-global-jaap": "Today's Global Jaap",
  "dashboard.active-devotees": "Active Devotees",
  "dashboard.milestones": "Milestones",
  "dashboard.days": "Days",
  "dashboard.achieved": "Achieved",
  "dashboard.jaaps": "jaaps",
  "dashboard.reward": "reward",
  "dashboard.active-sankalp": "Active Sankalp",
  "dashboard.remaining": "Remaining",
  "dashboard.progress": "Progress",

  // Admin Dashboard
  "admin.dash.title": "Sewa Live Report",
  "admin.dash.subtitle": "Real-time jaap data — updates every 3 seconds",
  "admin.dash.today-jaap": "Today's Jaap",
  "admin.dash.today-jaap-desc": "All devotees combined today",
  "admin.dash.today-expense": "Today's Expense",
  "admin.dash.total-jaap": "Total Jaap (All Days)",
  "admin.dash.since-start": "Since beginning",
  "admin.dash.total-expense": "Total Expense",
  "admin.dash.active-bhakts": "Active Devotees Today",
  "admin.dash.jaap-today": "Chanted today",
  "admin.dash.sankalps": "Sankalps",
  "admin.dash.completed-count": "completed",
  "admin.dash.total-bhakts": "Total Devotees",
  "admin.dash.pending-approval": "pending approval",
  "admin.dash.sankalp-report": "Sankalp Progress — Yajamana Report",
  "admin.dash.sankalp-report-desc": "Each sankalp's jaap and budget status",
  "admin.dash.no-sankalp": "No sankalps found",
  "admin.dash.completed-badge": "Done",
  "admin.dash.today-added": "Today: +",
  "admin.dash.today-bhakts-section": "Active Devotees Today",
  "admin.dash.today-bhakts-desc": "Who chanted today — their count and earnings",
  "admin.dash.col-bhakt": "Devotee",
  "admin.dash.col-today-jaap": "Today's Jaap",
  "admin.dash.col-today-expense": "Today's Expense",
  "admin.dash.total": "Total",
  "admin.dash.budget": "Budget",
  "admin.dash.active-badge": "Active",
  "admin.dash.progress": "Progress",

  // Payout Management
  "payout.title": "Payment Management",
  "payout.subtitle": "View all bhakts' earnings and process payouts",
  "payout.pending-requests": "Pending Requests",
  "payout.total-paid": "Total Paid",
  "payout.total-earnings": "Total Earnings",
  "payout.active-bhakts": "Active Bhakts",
  "payout.transactions": "transactions",
  "payout.all-bhakts": "All bhakts' combined",
  "payout.approved-bhakts": "Approved bhakts",
  "payout.tab-pending": "Pending",
  "payout.tab-bhakts": "Bhakt Earnings",
  "payout.tab-history": "History",
  "payout.pending-title": "Pending Payout Requests",
  "payout.pending-desc": "Process bhakts' payment requests",
  "payout.no-pending": "No pending requests 🎉",
  "payout.bhakts-title": "Bhakts' Total Earnings",
  "payout.bhakts-desc": "Each bhakt's earnings and pending payouts",
  "payout.no-bhakts": "No approved bhakts",
  "payout.history-title": "Payment History",
  "payout.history-desc": "Record of all past payments",
  "payout.no-history": "No payments processed yet",
  "payout.col-date": "Date",
  "payout.col-bhakt": "Bhakt",
  "payout.col-upi": "UPI ID",
  "payout.col-amount": "Amount",
  "payout.col-actions": "Actions",
  "payout.col-city": "City",
  "payout.col-total-jaap": "Total Jaap",
  "payout.col-total-earning": "Total Earning",
  "payout.col-pending": "Pending Payout",
  "payout.col-available": "Available",
  "payout.col-method": "Method",
  "payout.col-status": "Status",
  "payout.col-note": "Note",
  "payout.pay": "Pay",
  "payout.reject": "Reject",
  "payout.confirm-title": "Confirm Payment",
  "payout.bhakt-label": "Bhakt",
  "payout.amount-label": "Amount",
  "payout.method-label": "Payment Method *",
  "payout.method-placeholder": "Select method...",
  "payout.note-label": "Note (optional)",
  "payout.note-placeholder": "Transaction ID or note...",
  "payout.cancel": "Cancel",
  "payout.processing": "Processing...",
  "payout.confirm-btn": "Confirm Payment",
  "payout.paid-status": "✓ Paid",
  "payout.rejected-status": "✗ Rejected",
  "payout.method-choose": "Please select a payment method",
  "payout.success-title": "✅ Payment Complete",
  "payout.success-desc": "sent successfully",
  "payout.rejected-toast-title": "Rejected",

  // Jaap Page
  "jaap.total": "Total Jaap",
  "jaap.mala": "Mala Count",
  "jaap.mala-desc": "1 mala = 108 jaap",
  "jaap.earnings": "Total Earnings",
  "jaap.todays-sadhana": "Today's Sadhana",
  "jaap.todays-jaap": "Today's Jaap",
  "jaap.box-today-jaap": "Today's Jaap",
  "jaap.box-today-earn": "Today's Earn",
  "jaap.box-total-jaap": "Total Jaap",
  "jaap.box-total-earn": "Total Earn",
  "jaap.tap-to-chant": "Tap in circle to chant",
  "jaap.bead": "Bead",
  "jaap.today": "Today",
  "jaap.milestone-title": "25,000 Jaap Offered!",
  "jaap.milestone-name": "25k Milestone!",
  "jaap.milestone-desc": "You have offered 25,000 Naam Jaap to Baba Shyam today.",
  "jaap.milestone-continue-q": "Would you like to continue?",
  "jaap.milestone-continue": "Yes, continue 🙏",
  "jaap.milestone-stop": "That's enough for today",
  "jaap.mute": "Mute sound",
  "jaap.unmute": "Unmute sound",
  "jaap.voice-on": "Turn off voice",
  "jaap.voice-off": "Turn on voice",

  // Sankalp Page — ALWAYS HINDI (spiritual ritual before jaap)
  "sankalp.title": "आज का संकल्प",
  "sankalp.subtitle": "आज का संकल्प लें",
  "sankalp.choose-title": "आज किसके लिए जाप करना है?",
  "sankalp.choose-desc": "एक संकल्प चुनें जिसके निमित्त आज का नाम जाप समर्पित करें",
  "sankalp.yajamana": "यजमान",
  "sankalp.gotra": "गोत्र",
  "sankalp.niwas": "निवास",
  "sankalp.accept": "संकल्प स्वीकार करें",
  "sankalp.accepting": "स्वीकार हो रहा है...",

  // Profile
  "profile.title": "Profile",
  "profile.subtitle": "Manage your devotee identity",
  "profile.logout": "Logout",
  "profile.full-name": "Full Name",
  "profile.gotra": "Gotra (Optional)",
  "profile.city": "City",
  "profile.state": "State",
  "profile.upi": "UPI ID",
  "profile.upi-desc": "Required to receive earnings payouts.",
  "profile.save": "Save Changes",
  "profile.saving": "Saving...",

  "profile.change-password": "Change Password",
  "profile.change-password-desc": "Only available for email/password accounts",
  "profile.current-password": "Current Password",
  "profile.new-password": "New Password (min. 6 characters)",
  "profile.confirm-password": "Confirm New Password",
  "profile.passwords-mismatch": "Passwords do not match",
  "profile.password-changed": "Password Changed",
  "profile.password-changed-desc": "Your password has been updated successfully.",
  "profile.password-wrong": "Current password is incorrect",
  "profile.password-min": "New password must be at least 6 characters",
  "profile.updating-password": "Updating...",
  "profile.update-password": "Update Password",
  "profile.approved": "Approved",
  "profile.pending": "Pending",
  "profile.updated-title": "Profile Updated",
  "profile.updated-desc": "Your details have been saved.",
  "profile.error": "Failed to update profile.",

  // Onboarding
  "onboarding.title": "Devotee Details",
  "onboarding.subtitle": "Complete your devotee profile to continue",
  "onboarding.full-name": "Full Name",
  "onboarding.gotra": "Gotra (Optional)",
  "onboarding.city": "City",
  "onboarding.state": "State",
  "onboarding.upi": "UPI ID (Optional)",
  "onboarding.submit": "Submit Profile",
  "onboarding.saving": "Saving...",

  // Wallet
  "wallet.title": "Wallet",
  "wallet.subtitle": "Manage your sadhana rewards",
  "wallet.available": "Available Balance",
  "wallet.request-payout": "Request Payout",
  "wallet.amount": "Amount (₹)",
  "wallet.min-note": "Minimum ₹10 required.",
  "wallet.upi": "UPI ID",
  "wallet.submit": "Submit Request",
  "wallet.submitting": "Submitting...",
  "wallet.min-balance": "Minimum balance of ₹10 required to withdraw.",
  "wallet.lifetime": "Lifetime Earnings",
  "wallet.total-earned": "Total Earned",
  "wallet.pending-payouts": "Pending Payouts",
  "wallet.total-withdrawn": "Total Withdrawn",
  "wallet.payout-history": "Payout History",
  "wallet.payout-history-desc": "Your recent withdrawal requests",
  "wallet.date": "Date",
  "wallet.amount-col": "Amount",
  "wallet.status": "Status",
  "wallet.no-payouts": "No payouts requested yet.",
  "wallet.payout-requested-title": "Payout Requested",
  "wallet.payout-requested-desc": "Your request is pending approval.",
  "wallet.payout-error": "Failed to request payout",
  "wallet.payout-dialog-title": "Request Payout",
  "wallet.status-paid": "paid",
  "wallet.status-pending": "pending",
  "wallet.status-rejected": "rejected",

  // Leaderboard
  "leaderboard.title": "Leaderboard",
  "leaderboard.subtitle": "Top devotees in the temple",
  "leaderboard.today": "Today",
  "leaderboard.week": "This Week",
  "leaderboard.alltime": "All Time",
  "leaderboard.you": "(You)",
  "leaderboard.jaaps": "jaaps",
  "leaderboard.empty": "No devotees found for this period.",

  // Sankalp History
  "history.title": "Sankalp History",
  "history.subtitle": "Your daily resolutions over the last 30 days",
  "history.last30": "Last 30 Days",
  "history.accepted": "Accepted",
  "history.missed": "Missed",
  "history.empty": "No history available yet.",

  // Mera Sankalp
  "mera.title": "My Sankalp",
  "mera.subtitle": "Yajamana Dashboard — complete account of active sankalps",
  "mera.total-accumulated": "Total Accumulated",
  "mera.of-goal": "of {n} goal",
  "mera.budget-used": "Budget Used",
  "mera.of-allocated": "of ₹{n} allocated",
  "mera.active-sankalps": "Active Sankalps",
  "mera.remaining-budget": "Remaining Budget",
  "mera.no-active": "No active sankalps",
  "mera.no-active-desc": "Create a new sankalp from the admin panel",
  "mera.active-heading": "Active Sankalps",
  "mera.gotra": "Gotra",
  "mera.pita": "Father",
  "mera.pati": "Husband",
  "mera.niwas": "Niwas",
  "mera.progress": "Sankalp Progress",
  "mera.complete": "complete",
  "mera.estimate": "Estimate",
  "mera.budget-allocated": "Budget Allocated",
  "mera.spent": "Spent So Far",
  "mera.deadline": "Deadline",
  "mera.open-ended": "Open-ended",
  "mera.completed-paused": "Completed / Paused",
  "mera.divangat": "Divangat",
  "mera.completed-label": "Completed!",
  "mera.years": "years",
  "mera.days": "days",
  "mera.na": "N/A",
  "mera.admin-required": "Admin access required",
  "mera.col-yajamana": "Yajamana",
  "mera.col-mantra": "Mantra",
  "mera.col-purpose": "Purpose",
  "mera.col-progress": "Progress",
  "mera.col-budget": "Budget",
  "mera.col-estimate": "Estimate",
  "mera.col-status": "Status",
  "mera.col-action": "Action",
  "mera.budget-used-label": "Used",
  "mera.budget-remaining-label": "Remaining",
  "mera.report-title": "Payment Report",
  "mera.col-sno": "S.No",
  "mera.ready-for-payment": "Ready for payment",
  "mera.no-contribution": "No contributions in this sankalp.",
  "mera.close": "Close",
  "mera.view-report": "View Report",

  // Sankalp Board
  "board.title": "Sankalp Board",
  "board.subtitle": "Your active spiritual goals",
  "board.active": "Active",
  "board.completed": "Completed",
  "board.locked": "Locked",
  "board.remaining": "Remaining",
  "board.progress": "Progress",
  "board.no-active": "No active sankalps yet",
  "board.complete-current": "Complete your current sankalp to unlock the next",
  "board.of": "of",
  "board.waiting-unlock": "Waiting to Unlock",
  "board.unlock-desc": "Complete the running sankalp to unlock these",
  "board.completed-count": "Completed",
  "board.total-label": "Total",
  "board.yours-label": "Yours",
  "board.all-sankalps": "All Sankalps",
  "board.col-sno": "S.No",
  "board.col-yajman": "Yajman",
  "board.col-purpose": "Purpose",
  "board.col-date": "Date",
  "board.col-jaap": "Jaap Count",
  "board.col-status": "Status",
  "board.col-actions": "Actions",
  "board.status-completed": "Completed",
  "board.status-running": "Running",
  "board.status-waiting": "Waiting",
  "board.contribution-title": "Your Contribution",
  "board.completed-contribution-title": "Sankalp Completed — Your Contribution",
  "board.loading": "Loading...",
  "board.total-jaaps-done": "Total Jaaps Done",
  "board.earning": "Earnings (₹)",
  "board.no-contribution": "You have not contributed to this sankalp yet.",
  "board.close": "Close",
  "board.report-admin-title": "Devotee Contribution Report",
  "board.report-my-title": "My Contribution",
  "board.total-contributors": "Total Contributors",
  "board.col-total-jaap": "Total Jaap",
  "board.col-bhakt": "Devotee Name",
  "board.col-earned": "Earned (₹)",
  "board.total-payment": "Total Payment",
  "board.no-contrib-sankalp": "No contributions in this sankalp.",
  "board.my-jaaps": "Your Jaaps in this Sankalp",
  "board.my-earnings": "Your Earnings",
  "board.sankalp-complete-mark": "Complete ✓",
  "board.devotion-msg": "Your contribution became part of this sacred sankalp. 🙏",
  "board.no-jaap-msg": "You have not chanted in this sankalp.",
  "board.report-btn": "Report",
  "board.my-contribution-btn": "My Contribution",

  // Pending
  "pending.heading": "Please Wait",
  "pending.welcome": "Welcome",
  "pending.message": "Your profile has been submitted and is awaiting darshan (approval) from the admin. Please check back later to begin your sadhana.",
  "pending.logout": "Logout",

  // Not Found
  "notfound.title": "404 Page Not Found",
  "notfound.desc": "Did you forget to add the page to the router?",

  // Admin
  "admin.title": "Temple Admin",
  "admin.subtitle": "Manage devotees, mantras, and sankalps",
  "admin.devotees": "Devotees",
  "admin.payouts": "Payout Requests",
  "admin.mantras": "Mantras",
  "admin.yajamanas": "Yajamanas",
  "admin.sankalps": "Patron Sankalps",
  "admin.approve": "Approve",
  "admin.revoke": "Revoke",
  "admin.process": "Process",
  "admin.add-mantra": "Add Mantra",
  "admin.edit-mantra": "Edit Mantra",
  "admin.add-yajamana": "Add Yajamana",
  "admin.edit-yajamana": "Edit Yajamana",
  "admin.add-sankalp": "New Sankalp",
  "admin.edit-sankalp": "Edit Sankalp",
  "admin.cancel": "Cancel",
  "admin.save": "Save",
  "admin.delete": "Delete",
  "admin.edit": "Edit",

  "admin.reset-btn": "Reset All Data",
  "admin.reset.title": "Reset All Jaap Data?",
  "admin.reset.body": "This action will zero out all devotees' jaap counts, daily records, and sankalp progress.",
  "admin.reset.warning": "This action cannot be undone!",
  "admin.reset.cancel": "Wait",
  "admin.reset.loading": "Resetting...",
  "admin.reset.confirm": "Yes, Reset",
  "admin.reset.success": "Data Reset",
  "admin.reset.success-desc": "All jaap counts have been zeroed.",

  "admin.pending.title": "new devotees awaiting approval",
  "admin.pending.desc": "Check the Devotees tab below",

  "admin.stats.total-users": "Total Users",
  "admin.stats.approved": "Approved:",
  "admin.stats.today-jaap": "Today's Jaap",
  "admin.stats.active-today": "Active today:",
  "admin.stats.pending-payouts": "Pending Payouts",
  "admin.stats.total-jaap": "Total Jaap:",
  "admin.stats.paid-out": "Paid Out",

  "admin.tab.devotees": "Devotees",
  "admin.tab.mantras": "Mantras",
  "admin.tab.yajamanas": "Yajamanas",
  "admin.tab.sankalps": "Sankalps",

  "admin.devotees.title": "Devotee Directory",
  "admin.devotees.desc": "Click a name to see full details",
  "admin.devotees.col-city": "City / State",
  "admin.devotees.col-jaap": "Jaap",
  "admin.devotees.col-income": "Income",
  "admin.devotees.col-approval": "Approved",
  "admin.devotees.updated": "Updated",
  "admin.devotees.approved-desc": "Devotee approved.",
  "admin.devotees.unapproved-desc": "Devotee unapproved.",

  "admin.mantras.desc": "Manage mantras available for naam jaap",
  "admin.mantras.col-script": "Mantra (Script)",
  "admin.mantras.col-display": "Display Name",
  "admin.mantras.empty": "No mantras found",
  "admin.mantra-form.updated": "Mantra updated",
  "admin.mantra-form.added": "Mantra added",
  "admin.mantra-form.deleted": "Mantra deleted",
  "admin.mantra-form.cannot-delete": "Cannot delete",
  "admin.mantra-form.cannot-delete-desc": "Cannot delete the default mantra or one that is in use",
  "admin.mantra-form.script-label": "Mantra Script (Hindi/Sanskrit)",
  "admin.mantra-form.display-label": "Display Name (English)",
  "admin.mantra-form.default-label": "Default Mantra",
  "admin.mantra-form.update-btn": "Update Mantra",

  "admin.yajamanas.desc": "Those in whose name the sankalp has been taken",
  "admin.yajamanas.col-gotra": "Gotra",
  "admin.yajamanas.col-father": "Father / Husband",
  "admin.yajamanas.col-niwas": "Location",
  "admin.yajamanas.col-relation": "Relation",
  "admin.yajamanas.living": "Living",
  "admin.yajamanas.divangat": "Departed",
  "admin.yajamanas.empty": "No yajamanas found",
  "admin.yajamana-form.updated": "Yajamana updated",
  "admin.yajamana-form.added": "Yajamana added",
  "admin.yajamana-form.deleted": "Yajamana deleted",
  "admin.yajamana-form.cannot-delete": "Cannot delete",
  "admin.yajamana-form.cannot-delete-desc": "Yajamana has an active sankalp",
  "admin.yajamana-form.gotra-label": "Gotra *",
  "admin.yajamana-form.relation-label": "Relation",
  "admin.yajamana-form.father-label": "Father's Name",
  "admin.yajamana-form.husband-label": "Husband's Name",
  "admin.yajamana-form.husband-placeholder": "(if applicable)",
  "admin.yajamana-form.niwas-label": "Place of Residence *",
  "admin.yajamana-form.jiwit": "Living",
  "admin.yajamana-form.divangat": "Departed",
  "admin.yajamana-form.update-btn": "Update Yajamana",

  "admin.sankalps.desc": "Active naam jaap goals on behalf of yajamanas",
  "admin.sankalps.col-type": "Type",
  "admin.sankalps.col-budget": "Budget",
  "admin.sankalps.view-report": "View Report",
  "admin.sankalps.contributors": "Contributors",
  "admin.sankalps.no-contrib": "No contributions yet.",
  "admin.sankalps.empty": "No sankalps. Please add a yajamana and mantra first.",
  "admin.sankalp-form.updated": "Sankalp updated",
  "admin.sankalp-form.created": "Sankalp created",
  "admin.sankalp-form.yajamana-placeholder": "Select yajamana",
  "admin.sankalp-form.mantra-placeholder": "Select mantra",
  "admin.sankalp-form.rate-label": "Rate per Jaap (₹)",
  "admin.sankalp-form.rate-desc": "how much a devotee earns per jaap",
  "admin.sankalp-form.goal-label": "Goal Count",
  "admin.sankalp-form.budget-label": "Budget (₹)",
  "admin.sankalp-form.purpose-label": "Sankalp Purpose *",
  "admin.sankalp-form.purpose-placeholder": "Health, blessings...",
  "admin.sankalp-form.deadline-label": "Deadline",
  "admin.sankalp-form.status-active": "Active",
  "admin.sankalp-form.status-paused": "Paused",
  "admin.sankalp-form.status-completed": "Completed",
  "admin.sankalp-form.type-label": "Sankalp Type",
  "admin.sankalp-form.public": "For All (Public)",
  "admin.sankalp-form.private": "Selected Devotees (Private)",
  "admin.sankalp-form.select-bhakts": "Select devotees (who will participate in this sankalp)",
  "admin.sankalp-form.no-approved": "No approved devotees.",
  "admin.sankalp-form.bhakts-selected": "devotees selected",
  "admin.sankalp-form.create-btn": "Create Sankalp",
  "admin.sankalp-form.update-btn": "Update Sankalp",

  "admin.report.title": "Payment Report",
  "admin.report.col-bhakt": "Devotee",
  "admin.report.col-jaap": "Jaap",
  "admin.report.col-amount": "Amount Due (₹)",
  "admin.report.total": "Total",
  "admin.report.no-contrib": "No contributions.",

  "admin.profile.title": "Devotee Profile",
  "admin.profile.total-jaap": "Total Jaap",
  "admin.profile.total-kamayi": "Total Earnings",
  "admin.profile.streak": "Streak",
  "admin.profile.days": "days",
  "admin.profile.joined": "Joined:",
  "admin.profile.sankalp-contrib": "Sankalp-wise Contribution",
  "admin.profile.col-sankalp": "Sankalp / Yajamana",
  "admin.profile.col-jaap": "Jaap",
  "admin.profile.col-kamayi": "Earnings",
  "admin.profile.recent-days": "Recent Jaap Days",
  "admin.profile.col-date": "Date",
  "admin.profile.payout-history": "Payout History",
  "admin.profile.col-amount": "Amount",
  "admin.profile.col-method": "Method",
  "admin.profile.load-failed": "Could not load profile.",

  // Common
  "common.name": "Name",
  "common.status": "Status",
  "common.actions": "Actions",
  "common.loading": "Loading...",
  "common.error": "Error",
  "common.success": "Success",
  "common.default": "Default",
  "common.language": "Language",

  // Contact Us
  "nav.contact": "Contact Us",
  "contact.title": "Contact Us",
  "contact.subtitle": "We're here to help you on your devotional journey.",
  "contact.whatsapp.label": "WhatsApp",
  "contact.whatsapp.number-label": "Our WhatsApp Number",
  "contact.whatsapp.desc": "Reach out to us directly on WhatsApp for any queries, support, or guidance regarding Naam Jap Sewa.",
  "contact.whatsapp.button": "Chat on WhatsApp",
  "contact.whatsapp.hint": "Tap the button to open WhatsApp and start a conversation.",
  "contact.hours.title": "Availability",
  "contact.hours.desc": "We typically respond within a few hours. Please be patient — our team is dedicated to serving every bhakt with care.",
  "contact.hours.time": "Mon – Sun, 9:00 AM – 9:00 PM (IST)",
  "contact.note.title": "How can we help?",
  "contact.note.desc": "You can reach us for registration help, sankalp queries, payout questions, or any other assistance related to our sewa.",
};

const hi: typeof en = {
  // Landing
  "landing.title": "नाम जप सेवा",
  "landing.subtitle": "\"हारे का सहारा, बाबा श्याम हमारा\"",
  "landing.description": "श्री खाटू श्याम जी के चरणों में नाम जाप की सेवा समर्पित करें। यजमानों के संकल्प पूर्ण करने में सहयोगी बनें, प्रतिदिन सेवा करें और बाबा की कृपा से दक्षिणा प्राप्त करें।",
  "landing.button": "साधना शुरू करें",
  "landing.tab-login": "लॉगिन",
  "landing.tab-register": "रजिस्टर",
  "landing.label-name": "आपका नाम",
  "landing.placeholder-name": "पूरा नाम लिखें",
  "landing.label-email": "ईमेल",
  "landing.placeholder-email": "आपका@ईमेल.com",
  "landing.label-password": "पासवर्ड",
  "landing.placeholder-password": "पासवर्ड",
  "landing.forgot-password": "पासवर्ड भूल गए?",
  "landing.btn-login": "लॉगिन करें",
  "landing.btn-register": "खाता बनाएं",
  "landing.btn-loading": "प्रतीक्षा करें...",
  "landing.error-required": "ईमेल और पासवर्ड आवश्यक हैं",
  "landing.error-name-required": "कृपया अपना नाम भरें",
  "landing.error-generic": "कुछ गलत हुआ, दोबारा कोशिश करें",

  // Layout Navigation
  "nav.jaap": "जाप",
  "nav.dashboard": "डैशबोर्ड",
  "nav.leaderboard": "लीडरबोर्ड",
  "nav.wallet": "वॉलेट",
  "nav.history": "इतिहास",
  "nav.profile": "प्रोफाइल",
  "nav.sankalp-board": "संकल्प बोर्ड",
  "nav.mera-sankalp": "मेरा संकल्प",
  "nav.admin": "प्रशासक",
  "nav.logout": "लॉगआउट",
  "nav.payout": "भुगतान",

  // Dashboard (Bhakt)
  "dashboard.title": "डैशबोर्ड",
  "dashboard.subtitle": "आपकी साधना का अवलोकन",
  "dashboard.daily-target": "दैनिक लक्ष्य",
  "dashboard.total-jaaps": "कुल जाप",
  "dashboard.streak": "लगातार",
  "dashboard.todays-earnings": "आज की आय",
  "dashboard.total-earnings": "कुल आय",
  "dashboard.daily-history": "पिछले 7 दिन",
  "dashboard.global-stats": "वैश्विक मंदिर",
  "dashboard.global-desc": "सभी भक्तों की सामूहिक भक्ति",
  "dashboard.global-jaap-count": "वैश्विक जाप संख्या",
  "dashboard.todays-global-jaap": "आज का वैश्विक जाप",
  "dashboard.active-devotees": "सक्रिय भक्त",
  "dashboard.milestones": "उपलब्धियाँ",
  "dashboard.days": "दिन",
  "dashboard.achieved": "प्राप्त",
  "dashboard.jaaps": "जाप",
  "dashboard.reward": "पुरस्कार",
  "dashboard.active-sankalp": "सक्रिय संकल्प",
  "dashboard.remaining": "शेष",
  "dashboard.progress": "प्रगति",

  // Admin Dashboard
  "admin.dash.title": "सेवा लाइव रिपोर्ट",
  "admin.dash.subtitle": "रियल-टाइम जाप डेटा — हर 3 सेकंड में अपडेट",
  "admin.dash.today-jaap": "आज के जाप",
  "admin.dash.today-jaap-desc": "सभी भक्तों का आज",
  "admin.dash.today-expense": "आज का खर्चा",
  "admin.dash.total-jaap": "कुल जाप (सब दिन)",
  "admin.dash.since-start": "शुरुआत से अब तक",
  "admin.dash.total-expense": "कुल खर्चा",
  "admin.dash.active-bhakts": "आज सक्रिय भक्त",
  "admin.dash.jaap-today": "आज जाप किया",
  "admin.dash.sankalps": "संकल्प",
  "admin.dash.completed-count": "पूरी हो गई",
  "admin.dash.total-bhakts": "कुल भक्त",
  "admin.dash.pending-approval": "अनुमोदन प्रतीक्षित",
  "admin.dash.sankalp-report": "संकल्प प्रगति — यजमान रिपोर्ट",
  "admin.dash.sankalp-report-desc": "हर संकल्प का जाप और बजट स्थिति",
  "admin.dash.no-sankalp": "कोई संकल्प नहीं मिला",
  "admin.dash.completed-badge": "पूरी",
  "admin.dash.today-added": "आज: +",
  "admin.dash.today-bhakts-section": "आज के सक्रिय भक्त",
  "admin.dash.today-bhakts-desc": "आज जिन्होंने जाप किया — उनका count और earnings",
  "admin.dash.col-bhakt": "भक्त",
  "admin.dash.col-today-jaap": "आज जाप",
  "admin.dash.col-today-expense": "आज खर्चा",
  "admin.dash.total": "कुल",
  "admin.dash.budget": "बजट",
  "admin.dash.active-badge": "सक्रिय",
  "admin.dash.progress": "प्रगति",

  // Payout Management
  "payout.title": "भुगतान प्रबंधन",
  "payout.subtitle": "सभी भक्तों की आय देखें और भुगतान प्रोसेस करें",
  "payout.pending-requests": "लंबित अनुरोध",
  "payout.total-paid": "कुल भुगतान",
  "payout.total-earnings": "कुल आय",
  "payout.active-bhakts": "सक्रिय भक्त",
  "payout.transactions": "लेनदेन",
  "payout.all-bhakts": "सभी भक्तों की",
  "payout.approved-bhakts": "अनुमोदित भक्त",
  "payout.tab-pending": "लंबित",
  "payout.tab-bhakts": "भक्त आय",
  "payout.tab-history": "इतिहास",
  "payout.pending-title": "लंबित भुगतान अनुरोध",
  "payout.pending-desc": "भक्तों के भुगतान अनुरोध प्रोसेस करें",
  "payout.no-pending": "कोई लंबित अनुरोध नहीं 🎉",
  "payout.bhakts-title": "भक्तों की कुल आय",
  "payout.bhakts-desc": "हर भक्त की आय और लंबित भुगतान",
  "payout.no-bhakts": "कोई अनुमोदित भक्त नहीं",
  "payout.history-title": "भुगतान इतिहास",
  "payout.history-desc": "सभी पिछले भुगतानों का रिकॉर्ड",
  "payout.no-history": "अभी तक कोई भुगतान नहीं",
  "payout.col-date": "तारीख",
  "payout.col-bhakt": "भक्त",
  "payout.col-upi": "UPI आईडी",
  "payout.col-amount": "राशि",
  "payout.col-actions": "कार्य",
  "payout.col-city": "शहर",
  "payout.col-total-jaap": "कुल जाप",
  "payout.col-total-earning": "कुल आय",
  "payout.col-pending": "लंबित भुगतान",
  "payout.col-available": "उपलब्ध",
  "payout.col-method": "विधि",
  "payout.col-status": "स्थिति",
  "payout.col-note": "नोट",
  "payout.pay": "भुगतान करें",
  "payout.reject": "अस्वीकार",
  "payout.confirm-title": "भुगतान की पुष्टि करें",
  "payout.bhakt-label": "भक्त",
  "payout.amount-label": "राशि",
  "payout.method-label": "भुगतान विधि *",
  "payout.method-placeholder": "विधि चुनें...",
  "payout.note-label": "नोट (वैकल्पिक)",
  "payout.note-placeholder": "लेनदेन आईडी या नोट...",
  "payout.cancel": "रद्द करें",
  "payout.processing": "प्रोसेस हो रहा है...",
  "payout.confirm-btn": "भुगतान पुष्टि करें",
  "payout.paid-status": "✓ भुगतान हुआ",
  "payout.rejected-status": "✗ अस्वीकृत",
  "payout.method-choose": "भुगतान विधि चुनें",
  "payout.success-title": "✅ भुगतान सम्पन्न",
  "payout.success-desc": "को भेजा गया",
  "payout.rejected-toast-title": "अस्वीकृत",

  // Jaap Page
  "jaap.total": "कुल जाप",
  "jaap.mala": "माला गणना",
  "jaap.mala-desc": "1 माला = 108 जाप",
  "jaap.earnings": "कुल आय",
  "jaap.todays-sadhana": "आज की साधना",
  "jaap.todays-jaap": "आज का जाप",
  "jaap.box-today-jaap": "आज जाप",
  "jaap.box-today-earn": "आज आय",
  "jaap.box-total-jaap": "कुल जाप",
  "jaap.box-total-earn": "कुल आय",
  "jaap.tap-to-chant": "जाप करने के लिए वृत्त पर स्पर्श करें",
  "jaap.bead": "मनका",
  "jaap.today": "आज",
  "jaap.milestone-title": "25,000 जाप समर्पित!",
  "jaap.milestone-name": "25 हजार का मील का पत्थर!",
  "jaap.milestone-desc": "आपने आज बाबा श्याम को 25,000 नाम जाप समर्पित कर दिए।",
  "jaap.milestone-continue-q": "क्या आप आगे जारी रखना चाहते हैं?",
  "jaap.milestone-continue": "हाँ, आगे बढ़ूँ 🙏",
  "jaap.milestone-stop": "बस, आज के लिए इतना",
  "jaap.mute": "ध्वनि बंद करें",
  "jaap.unmute": "ध्वनि चालू करें",
  "jaap.voice-on": "आवाज़ बंद करें",
  "jaap.voice-off": "आवाज़ से जाप करें",

  // Sankalp Page — ALWAYS HINDI
  "sankalp.title": "आज का संकल्प",
  "sankalp.subtitle": "आज का संकल्प लें",
  "sankalp.choose-title": "आज किसके लिए जाप करना है?",
  "sankalp.choose-desc": "एक संकल्प चुनें जिसके निमित्त आज का नाम जाप समर्पित करें",
  "sankalp.yajamana": "यजमान",
  "sankalp.gotra": "गोत्र",
  "sankalp.niwas": "निवास",
  "sankalp.accept": "संकल्प स्वीकार करें",
  "sankalp.accepting": "स्वीकार हो रहा है...",

  // Profile
  "profile.title": "प्रोफाइल",
  "profile.subtitle": "अपनी भक्त पहचान प्रबंधित करें",
  "profile.logout": "लॉगआउट",
  "profile.full-name": "पूरा नाम",
  "profile.gotra": "गोत्र (वैकल्पिक)",
  "profile.city": "शहर",
  "profile.state": "राज्य",
  "profile.upi": "UPI आईडी",
  "profile.upi-desc": "आय भुगतान प्राप्त करने के लिए आवश्यक।",
  "profile.save": "परिवर्तन सहेजें",
  "profile.saving": "सहेज रहा है...",

  "profile.change-password": "पासवर्ड बदलें",
  "profile.change-password-desc": "केवल ईमेल/पासवर्ड अकाउंट के लिए उपलब्ध",
  "profile.current-password": "वर्तमान पासवर्ड",
  "profile.new-password": "नया पासवर्ड (कम से कम 6 अक्षर)",
  "profile.confirm-password": "नया पासवर्ड दोबारा लिखें",
  "profile.passwords-mismatch": "पासवर्ड मेल नहीं खाते",
  "profile.password-changed": "पासवर्ड बदला गया",
  "profile.password-changed-desc": "आपका पासवर्ड सफलतापूर्वक अपडेट हो गया।",
  "profile.password-wrong": "वर्तमान पासवर्ड गलत है",
  "profile.password-min": "नया पासवर्ड कम से कम 6 अक्षर का होना चाहिए",
  "profile.updating-password": "अपडेट हो रहा है...",
  "profile.update-password": "पासवर्ड अपडेट करें",
  "profile.approved": "अनुमोदित",
  "profile.pending": "प्रतीक्षारत",
  "profile.updated-title": "प्रोफाइल अपडेट हुई",
  "profile.updated-desc": "आपका विवरण सहेजा गया।",
  "profile.error": "प्रोफाइल अपडेट करने में विफल।",

  // Onboarding
  "onboarding.title": "भक्त विवरण",
  "onboarding.subtitle": "जारी रखने के लिए अपनी भक्त प्रोफाइल पूरी करें",
  "onboarding.full-name": "पूरा नाम",
  "onboarding.gotra": "गोत्र (वैकल्पिक)",
  "onboarding.city": "शहर",
  "onboarding.state": "राज्य",
  "onboarding.upi": "UPI आईडी (वैकल्पिक)",
  "onboarding.submit": "प्रोफाइल जमा करें",
  "onboarding.saving": "सहेज रहा है...",

  // Wallet
  "wallet.title": "वॉलेट",
  "wallet.subtitle": "अपनी साधना पुरस्कार प्रबंधित करें",
  "wallet.available": "उपलब्ध शेष",
  "wallet.request-payout": "भुगतान अनुरोध करें",
  "wallet.amount": "राशि (₹)",
  "wallet.min-note": "न्यूनतम ₹10 आवश्यक।",
  "wallet.upi": "UPI आईडी",
  "wallet.submit": "अनुरोध भेजें",
  "wallet.submitting": "भेज रहा है...",
  "wallet.min-balance": "निकासी के लिए न्यूनतम ₹10 शेष आवश्यक।",
  "wallet.lifetime": "आजीवन आय",
  "wallet.total-earned": "कुल अर्जित",
  "wallet.pending-payouts": "प्रतीक्षारत भुगतान",
  "wallet.total-withdrawn": "कुल निकाला",
  "wallet.payout-history": "भुगतान इतिहास",
  "wallet.payout-history-desc": "आपके हालिया निकासी अनुरोध",
  "wallet.date": "तारीख",
  "wallet.amount-col": "राशि",
  "wallet.status": "स्थिति",
  "wallet.no-payouts": "अभी तक कोई भुगतान अनुरोध नहीं।",
  "wallet.payout-requested-title": "भुगतान अनुरोध किया गया",
  "wallet.payout-requested-desc": "आपका अनुरोध अनुमोदन के लिए प्रतीक्षारत है।",
  "wallet.payout-error": "भुगतान अनुरोध विफल",
  "wallet.payout-dialog-title": "भुगतान अनुरोध करें",
  "wallet.status-paid": "भुगतान हुआ",
  "wallet.status-pending": "प्रतीक्षारत",
  "wallet.status-rejected": "अस्वीकृत",

  // Leaderboard
  "leaderboard.title": "लीडरबोर्ड",
  "leaderboard.subtitle": "मंदिर के शीर्ष भक्त",
  "leaderboard.today": "आज",
  "leaderboard.week": "इस सप्ताह",
  "leaderboard.alltime": "सर्वकालिक",
  "leaderboard.you": "(आप)",
  "leaderboard.jaaps": "जाप",
  "leaderboard.empty": "इस अवधि के लिए कोई भक्त नहीं मिला।",

  // Sankalp History
  "history.title": "संकल्प इतिहास",
  "history.subtitle": "पिछले 30 दिनों में आपके दैनिक संकल्प",
  "history.last30": "पिछले 30 दिन",
  "history.accepted": "स्वीकृत",
  "history.missed": "छूटा",
  "history.empty": "अभी तक कोई इतिहास उपलब्ध नहीं।",

  // Mera Sankalp
  "mera.title": "मेरा संकल्प",
  "mera.subtitle": "यजमान डैशबोर्ड — आपके सक्रिय संकल्पों का पूरा हिसाब",
  "mera.total-accumulated": "कुल संचित",
  "mera.of-goal": "{n} लक्ष्य में से",
  "mera.budget-used": "बजट उपयोग",
  "mera.of-allocated": "₹{n} में से",
  "mera.active-sankalps": "सक्रिय संकल्प",
  "mera.remaining-budget": "शेष बजट",
  "mera.no-active": "कोई सक्रिय संकल्प नहीं है",
  "mera.no-active-desc": "प्रशासक पैनल से नया संकल्प बनाएं",
  "mera.active-heading": "सक्रिय संकल्प",
  "mera.gotra": "गोत्र",
  "mera.pita": "पिता",
  "mera.pati": "पति",
  "mera.niwas": "निवास",
  "mera.progress": "संकल्प प्रगति",
  "mera.complete": "पूर्ण",
  "mera.estimate": "अनुमान",
  "mera.budget-allocated": "आवंटित बजट",
  "mera.spent": "अब तक खर्च",
  "mera.deadline": "समय सीमा",
  "mera.open-ended": "अनिश्चितकालीन",
  "mera.completed-paused": "पूर्ण / रुके हुए",
  "mera.divangat": "दिवंगत",
  "mera.completed-label": "पूर्ण!",
  "mera.years": "वर्ष",
  "mera.days": "दिन",
  "mera.na": "N/A",
  "mera.admin-required": "प्रशासक अनुमति आवश्यक",
  "mera.col-yajamana": "यजमान",
  "mera.col-mantra": "मंत्र",
  "mera.col-purpose": "संकल्प",
  "mera.col-progress": "प्रगति",
  "mera.col-budget": "बजट",
  "mera.col-estimate": "अनुमान",
  "mera.col-status": "स्थिति",
  "mera.col-action": "कार्य",
  "mera.budget-used-label": "उपयोग",
  "mera.budget-remaining-label": "शेष",
  "mera.report-title": "भुगतान रिपोर्ट",
  "mera.col-sno": "क्रम",
  "mera.ready-for-payment": "भुगतान के लिए तैयार",
  "mera.no-contribution": "इस संकल्प में कोई योगदान नहीं है।",
  "mera.close": "बंद करें",
  "mera.view-report": "रिपोर्ट देखें",

  // Sankalp Board
  "board.title": "संकल्प बोर्ड",
  "board.subtitle": "आपके सक्रिय आध्यात्मिक लक्ष्य",
  "board.active": "सक्रिय",
  "board.completed": "पूरा",
  "board.locked": "बंद",
  "board.remaining": "बाकी",
  "board.progress": "प्रगति",
  "board.no-active": "अभी कोई सक्रिय संकल्प नहीं",
  "board.complete-current": "अगला अनलॉक करने के लिए वर्तमान संकल्प पूरा करें",
  "board.of": "का",
  "board.waiting-unlock": "अनलॉक होने की प्रतीक्षा में",
  "board.unlock-desc": "इन्हें अनलॉक करने के लिए चालू संकल्प पूरा करें",
  "board.completed-count": "पूर्ण",
  "board.total-label": "कुल",
  "board.yours-label": "आपका",
  "board.all-sankalps": "सभी संकल्प",
  "board.col-sno": "क्रम",
  "board.col-yajman": "यजमान",
  "board.col-purpose": "संकल्प",
  "board.col-date": "तारीख",
  "board.col-jaap": "जाप संख्या",
  "board.col-status": "स्थिति",
  "board.col-actions": "कार्य",
  "board.status-completed": "पूर्ण",
  "board.status-running": "चल रहा है",
  "board.status-waiting": "प्रतीक्षा",
  "board.contribution-title": "आपका योगदान",
  "board.completed-contribution-title": "संकल्प पूर्ण — आपका योगदान",
  "board.loading": "लोड हो रहा है...",
  "board.total-jaaps-done": "कुल जाप किए",
  "board.earning": "कमाई (₹)",
  "board.no-contribution": "आपने इस संकल्प में अभी कोई योगदान नहीं दिया है।",
  "board.close": "बंद करें",
  "board.report-admin-title": "भक्त योगदान रिपोर्ट",
  "board.report-my-title": "मेरा योगदान",
  "board.total-contributors": "कुल योगदानकर्ता",
  "board.col-total-jaap": "कुल जाप",
  "board.col-bhakt": "भक्त का नाम",
  "board.col-earned": "अर्जित राशि (₹)",
  "board.total-payment": "कुल भुगतान",
  "board.no-contrib-sankalp": "इस संकल्प में कोई योगदान नहीं है।",
  "board.my-jaaps": "इस संकल्प में आपके जाप",
  "board.my-earnings": "आपकी कमाई",
  "board.sankalp-complete-mark": "पूर्ण ✓",
  "board.devotion-msg": "आपका योगदान इस पवित्र संकल्प का हिस्सा बना। 🙏",
  "board.no-jaap-msg": "इस संकल्प में आपने कोई जाप नहीं किया।",
  "board.report-btn": "रिपोर्ट",
  "board.my-contribution-btn": "मेरा योगदान",

  // Pending
  "pending.heading": "प्रतीक्षा करें",
  "pending.welcome": "स्वागत है",
  "pending.message": "आपकी प्रोफाइल जमा हो गई है और प्रशासक के दर्शन (अनुमोदन) की प्रतीक्षा कर रही है। अपनी साधना शुरू करने के लिए बाद में देखें।",
  "pending.logout": "लॉगआउट",

  // Not Found
  "notfound.title": "404 - पृष्ठ नहीं मिला",
  "notfound.desc": "यह पृष्ठ उपलब्ध नहीं है।",

  // Admin
  "admin.title": "मंदिर प्रशासन",
  "admin.subtitle": "भक्त, मंत्र और संकल्प प्रबंधित करें",
  "admin.devotees": "भक्त",
  "admin.payouts": "भुगतान अनुरोध",
  "admin.mantras": "मंत्र",
  "admin.yajamanas": "यजमान",
  "admin.sankalps": "संकल्प",
  "admin.approve": "अनुमति दें",
  "admin.revoke": "रद्द करें",
  "admin.process": "संसाधित करें",
  "admin.add-mantra": "मंत्र जोड़ें",
  "admin.edit-mantra": "मंत्र संपादित करें",
  "admin.add-yajamana": "यजमान जोड़ें",
  "admin.edit-yajamana": "यजमान संपादित करें",
  "admin.add-sankalp": "नया संकल्प",
  "admin.edit-sankalp": "संकल्प संपादित करें",
  "admin.cancel": "रद्द करें",
  "admin.save": "सहेजें",
  "admin.delete": "हटाएं",
  "admin.edit": "संपादित करें",

  "admin.reset-btn": "सभी डेटा रीसेट करें",
  "admin.reset.title": "सभी जाप डेटा रीसेट करें?",
  "admin.reset.body": "यह कार्य सभी भक्तों के जाप गणना, दैनिक रिकॉर्ड और संकल्प प्रगति को शून्य कर देगा।",
  "admin.reset.warning": "यह कार्य पूर्ववत नहीं हो सकता!",
  "admin.reset.cancel": "रुको",
  "admin.reset.loading": "रीसेट हो रहा है...",
  "admin.reset.confirm": "हाँ, रीसेट करो",
  "admin.reset.success": "डेटा रीसेट",
  "admin.reset.success-desc": "सभी जाप गणनाएं शून्य हो गई।",

  "admin.pending.title": "नए भक्त अनुमति की प्रतीक्षा में",
  "admin.pending.desc": "नीचे भक्त टैब में देखें",

  "admin.stats.total-users": "कुल उपयोगकर्ता",
  "admin.stats.approved": "अनुमोदित:",
  "admin.stats.today-jaap": "आज के जाप",
  "admin.stats.active-today": "आज सक्रिय:",
  "admin.stats.pending-payouts": "लंबित भुगतान",
  "admin.stats.total-jaap": "कुल जाप:",
  "admin.stats.paid-out": "भुगतान किया",

  "admin.tab.devotees": "भक्त",
  "admin.tab.mantras": "मंत्र",
  "admin.tab.yajamanas": "यजमान",
  "admin.tab.sankalps": "संकल्प",

  "admin.devotees.title": "भक्त सूची",
  "admin.devotees.desc": "नाम पर क्लिक करें पूरी जानकारी देखें",
  "admin.devotees.col-city": "शहर / राज्य",
  "admin.devotees.col-jaap": "जाप",
  "admin.devotees.col-income": "आय",
  "admin.devotees.col-approval": "अनुमति",
  "admin.devotees.updated": "अपडेट हुआ",
  "admin.devotees.approved-desc": "भक्त को अनुमति दी गई।",
  "admin.devotees.unapproved-desc": "भक्त की अनुमति रद्द की गई।",

  "admin.mantras.desc": "नाम जाप के लिए उपलब्ध मंत्र प्रबंधित करें",
  "admin.mantras.col-script": "मंत्र (लिपि)",
  "admin.mantras.col-display": "प्रदर्शन नाम",
  "admin.mantras.empty": "कोई मंत्र नहीं मिला",
  "admin.mantra-form.updated": "मंत्र अपडेट हुआ",
  "admin.mantra-form.added": "मंत्र जोड़ा गया",
  "admin.mantra-form.deleted": "मंत्र हटाया गया",
  "admin.mantra-form.cannot-delete": "हटा नहीं सकते",
  "admin.mantra-form.cannot-delete-desc": "डिफ़ॉल्ट मंत्र या उपयोग में आने वाले मंत्र को हटाया नहीं जा सकता",
  "admin.mantra-form.script-label": "मंत्र लिपि (हिंदी/संस्कृत)",
  "admin.mantra-form.display-label": "प्रदर्शन नाम (English)",
  "admin.mantra-form.default-label": "डिफ़ॉल्ट मंत्र",
  "admin.mantra-form.update-btn": "मंत्र अपडेट करें",

  "admin.yajamanas.desc": "जिनके निमित्त संकल्प लिया गया है",
  "admin.yajamanas.col-gotra": "गोत्र",
  "admin.yajamanas.col-father": "पिता / पति",
  "admin.yajamanas.col-niwas": "निवास",
  "admin.yajamanas.col-relation": "संबंध",
  "admin.yajamanas.living": "जीवित",
  "admin.yajamanas.divangat": "दिवंगत",
  "admin.yajamanas.empty": "कोई यजमान नहीं मिला",
  "admin.yajamana-form.updated": "यजमान अपडेट हुआ",
  "admin.yajamana-form.added": "यजमान जोड़ा गया",
  "admin.yajamana-form.deleted": "यजमान हटाया गया",
  "admin.yajamana-form.cannot-delete": "हटा नहीं सकते",
  "admin.yajamana-form.cannot-delete-desc": "यजमान का कोई सक्रिय संकल्प है",
  "admin.yajamana-form.gotra-label": "गोत्र *",
  "admin.yajamana-form.relation-label": "संबंध",
  "admin.yajamana-form.father-label": "पिता जी का नाम",
  "admin.yajamana-form.husband-label": "पति जी का नाम",
  "admin.yajamana-form.husband-placeholder": "(यदि लागू हो)",
  "admin.yajamana-form.niwas-label": "निवास स्थान *",
  "admin.yajamana-form.jiwit": "जीवित",
  "admin.yajamana-form.divangat": "दिवंगत",
  "admin.yajamana-form.update-btn": "यजमान अपडेट करें",

  "admin.sankalps.desc": "यजमानों की ओर से सक्रिय नाम जाप लक्ष्य",
  "admin.sankalps.col-type": "प्रकार",
  "admin.sankalps.col-budget": "बजट",
  "admin.sankalps.view-report": "रिपोर्ट देखें",
  "admin.sankalps.contributors": "भक्तों द्वारा योगदान",
  "admin.sankalps.no-contrib": "अभी कोई योगदान नहीं है।",
  "admin.sankalps.empty": "कोई संकल्प नहीं है। पहले यजमान और मंत्र जोड़ें।",
  "admin.sankalp-form.updated": "संकल्प अपडेट हुआ",
  "admin.sankalp-form.created": "संकल्प बनाया गया",
  "admin.sankalp-form.yajamana-placeholder": "यजमान चुनें",
  "admin.sankalp-form.mantra-placeholder": "मंत्र चुनें",
  "admin.sankalp-form.rate-label": "प्रति जाप दर (₹)",
  "admin.sankalp-form.rate-desc": "एक जाप पर भक्त को कितना मिलेगा",
  "admin.sankalp-form.goal-label": "लक्ष्य संख्या",
  "admin.sankalp-form.budget-label": "बजट (₹)",
  "admin.sankalp-form.purpose-label": "संकल्प का उद्देश्य *",
  "admin.sankalp-form.purpose-placeholder": "स्वास्थ्य लाभ, मंगल कामनाएं...",
  "admin.sankalp-form.deadline-label": "समय सीमा",
  "admin.sankalp-form.status-active": "सक्रिय",
  "admin.sankalp-form.status-paused": "रुका हुआ",
  "admin.sankalp-form.status-completed": "पूर्ण",
  "admin.sankalp-form.type-label": "संकल्प प्रकार",
  "admin.sankalp-form.public": "सभी के लिए (Public)",
  "admin.sankalp-form.private": "चुने हुए भक्त (Private)",
  "admin.sankalp-form.select-bhakts": "भक्त चुनें (जो इस संकल्प में भाग लेंगे)",
  "admin.sankalp-form.no-approved": "कोई अनुमोदित भक्त नहीं है।",
  "admin.sankalp-form.bhakts-selected": "भक्त चुने गए",
  "admin.sankalp-form.create-btn": "संकल्प बनाएं",
  "admin.sankalp-form.update-btn": "संकल्प अपडेट करें",

  "admin.report.title": "भुगतान रिपोर्ट",
  "admin.report.col-bhakt": "भक्त",
  "admin.report.col-jaap": "जाप",
  "admin.report.col-amount": "देय राशि (₹)",
  "admin.report.total": "कुल",
  "admin.report.no-contrib": "कोई योगदान नहीं।",

  "admin.profile.title": "भक्त प्रोफाइल",
  "admin.profile.total-jaap": "कुल जाप",
  "admin.profile.total-kamayi": "कुल कमाई",
  "admin.profile.streak": "लगातार",
  "admin.profile.days": "दिन",
  "admin.profile.joined": "शामिल हुए:",
  "admin.profile.sankalp-contrib": "संकल्प-वार योगदान",
  "admin.profile.col-sankalp": "संकल्प / यजमान",
  "admin.profile.col-jaap": "जाप",
  "admin.profile.col-kamayi": "कमाई",
  "admin.profile.recent-days": "हाल के जाप दिवस",
  "admin.profile.col-date": "तारीख",
  "admin.profile.payout-history": "भुगतान इतिहास",
  "admin.profile.col-amount": "राशि",
  "admin.profile.col-method": "तरीका",
  "admin.profile.load-failed": "प्रोफाइल लोड नहीं हुई।",

  // Common
  "common.name": "नाम",
  "common.status": "स्थिति",
  "common.actions": "कार्य",
  "common.loading": "लोड हो रहा है...",
  "common.error": "त्रुटि",
  "common.success": "सफलता",
  "common.default": "डिफ़ॉल्ट",
  "common.language": "भाषा",

  // Contact Us
  "nav.contact": "संपर्क करें",
  "contact.title": "संपर्क करें",
  "contact.subtitle": "हम आपकी भक्ति यात्रा में सहायता के लिए सदैव तत्पर हैं।",
  "contact.whatsapp.label": "WhatsApp",
  "contact.whatsapp.number-label": "हमारा WhatsApp नंबर",
  "contact.whatsapp.desc": "नाम जप सेवा से संबंधित किसी भी प्रश्न, सहायता या मार्गदर्शन के लिए सीधे WhatsApp पर संपर्क करें।",
  "contact.whatsapp.button": "WhatsApp पर बात करें",
  "contact.whatsapp.hint": "बटन दबाएं और WhatsApp पर बातचीत शुरू करें।",
  "contact.hours.title": "उपलब्धता",
  "contact.hours.desc": "हम सामान्यतः कुछ घंटों में उत्तर देते हैं। कृपया धैर्य रखें — हमारी टीम प्रत्येक भक्त की सेवा में समर्पित है।",
  "contact.hours.time": "सोम – रवि, प्रातः 9:00 – सायं 9:00 (IST)",
  "contact.note.title": "हम किस विषय में सहायता कर सकते हैं?",
  "contact.note.desc": "पंजीकरण, संकल्प, भुगतान या नाम जप सेवा से जुड़े किसी भी प्रश्न के लिए हमसे संपर्क करें।",
};

export const translations = { en, hi };

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("hi");

  useEffect(() => {
    const saved = localStorage.getItem("language") as Language | null;
    if (saved) setLanguageState(saved);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || (translations.en as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
